In [60]:
l = [12,432,563,1234,865,-112] #this is a list

In [61]:
l

[12, 432, 563, 1234, 865, -112]

In [62]:
#build into Python, is called array array - not used as it lacks versitile

In [63]:
import numpy as np

In [64]:
a = np.array(l)

In [65]:
a

array([  12,  432,  563, 1234,  865, -112])

In [66]:
b = np.array([12, 123, 213, 63.2, "a"])

In [67]:
b

array(['12', '123', '213', '63.2', 'a'], 
      dtype='<U32')

In [68]:
print(b)

['12' '123' '213' '63.2' 'a']


In [69]:
#---- Array can only contain the same data type - in the above example it's converted into strings

In [70]:
type(b)

numpy.ndarray

In [71]:
type(l)

list

In [72]:
l.pop()

-112

In [73]:
l

[12, 432, 563, 1234, 865]

In [74]:
a

array([  12,  432,  563, 1234,  865, -112])

In [75]:
a.mean()

499.0

In [76]:
b

array(['12', '123', '213', '63.2', 'a'], 
      dtype='<U32')

In [77]:
b.mean()

TypeError: cannot perform reduce with flexible type

In [78]:
ab = np.array([1,2,12,12,123.123,123.213])

In [79]:
ab

array([   1.   ,    2.   ,   12.   ,   12.   ,  123.123,  123.213])

In [80]:
ab.mean()

45.556000000000004

---

In [81]:
#---- Slicing

In [82]:
l

[12, 432, 563, 1234, 865]

In [83]:
l[0:2]

[12, 432]

In [84]:
#---- Array slicing

In [85]:
a

array([  12,  432,  563, 1234,  865, -112])

In [86]:
a[2:]

array([ 563, 1234,  865, -112])

In [87]:
a[2:4]

array([ 563, 1234])

In [88]:
list(a)

[12, 432, 563, 1234, 865, -112]

In [92]:
b = a[2:4] # not creating a copy - creates a view

In [93]:
b

array([ 563, 1234])

In [94]:
b[0]

563

In [95]:
b[:]

array([ 563, 1234])

In [96]:
b[:] = 111

In [97]:
b

array([111, 111])

In [99]:
a # the data has been replaced with 111

array([  12,  432,  111,  111,  865, -112])

In [104]:
c = a.copy() #have to call this method to create a copy when slicing

In [105]:
c[0] = 0

In [106]:
c

array([   0,  432,  111,  111,  865, -112])

In [107]:
a

array([  12,  432,  111,  111,  865, -112])