In [2]:
#Data 
revenue = [14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 10305.32, 14379.96, 10713.97, 15433.50]
expenses = [12051.82, 5695.07, 12319.20, 12089.72, 8658.57, 840.20, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96]

In [3]:
import numpy as np

In [4]:
profit = np.array(revenue) - np.array(expenses)

In [5]:
profit

array([  2522.67,   1911.39,  -3707.79,  -2914.31,   -599.92,   7265.24,
         8210.55,   3944.97,   3328.39,  -2238.65,    659.6 ,  11629.54])

In [6]:
type(profit)

numpy.ndarray

In [7]:
list(profit)

[2522.6700000000001,
 1911.3900000000003,
 -3707.7900000000009,
 -2914.3099999999995,
 -599.92000000000007,
 7265.2399999999998,
 8210.5500000000011,
 3944.9700000000003,
 3328.3899999999994,
 -2238.6500000000015,
 659.59999999999854,
 11629.540000000001]

In [8]:
np.around(profit, 0)

array([  2523.,   1911.,  -3708.,  -2914.,   -600.,   7265.,   8211.,
         3945.,   3328.,  -2239.,    660.,  11630.])

In [9]:
list(profit)

[2522.6700000000001,
 1911.3900000000003,
 -3707.7900000000009,
 -2914.3099999999995,
 -599.92000000000007,
 7265.2399999999998,
 8210.5500000000011,
 3944.9700000000003,
 3328.3899999999994,
 -2238.6500000000015,
 659.59999999999854,
 11629.540000000001]

In [10]:
total_profit = np.around(profit, 0)

In [11]:
total_profit

array([  2523.,   1911.,  -3708.,  -2914.,   -600.,   7265.,   8211.,
         3945.,   3328.,  -2239.,    660.,  11630.])

In [12]:
list(total_profit)

[2523.0,
 1911.0,
 -3708.0,
 -2914.0,
 -600.0,
 7265.0,
 8211.0,
 3945.0,
 3328.0,
 -2239.0,
 660.0,
 11630.0]

In [13]:
tax_percent = 30

In [21]:
profit_after_tax = profit - (profit / 100 * tax_percent)

In [22]:
profit_after_tax

array([ 1765.869,  1337.973, -2595.453, -2040.017,  -419.944,  5085.668,
        5747.385,  2761.479,  2329.873, -1567.055,   461.72 ,  8140.678])

In [23]:
profit_margin = np.array(profit_after_tax) / np.array(revenue)

In [24]:
profit_margin

array([ 0.12116163,  0.17589956, -0.30139698, -0.22233524, -0.05211096,
        0.62743886,  0.49993433,  0.28276199,  0.22608449, -0.10897492,
        0.04309514,  0.52746804])

In [26]:
total_profit_margin = []

In [27]:
for i in range(0, len(profit_margin)):
    total_profit_margin.append(profit_margin[i] * 100)

In [28]:
total_profit_margin

[12.116163241389581,
 17.589956431769842,
 -30.139698376920858,
 -22.233524169492153,
 -5.2110961513404863,
 62.743885587950807,
 49.993432658216399,
 28.276198560529341,
 22.60844884001661,
 -10.897492065346503,
 4.3095136536689855,
 52.746804030194063]